In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd                  #data processing e.g. reading files (pd.read_csv)
import numpy as np                   #linear algebra
import matplotlib.pyplot as plt      #plotting and visualization
import seaborn as sns                #visualization
import nltk
from nltk.corpus import stopwords
import requests
import warnings
warnings.filterwarnings('ignore')
plt.rcParams['figure.figsize'] = 8,4

%matplotlib inline

In [2]:
html1 = urlopen("https://www.yelp.com/search?find_desc=Restraunts%20&find_loc=nyc")
bsObj1 = BeautifulSoup(html1)

In [ ]:
#Get the Names Gyms
nameList = bsObj1.find_all('div', {'class': 'lemon--div__373c0__1mboc businessName__373c0__1fTgn border-color--default__373c0__2oFDT'})
for name in nameList:
    print(name.get_text())

In [46]:
#Get the harbor fitness reviews
urls = []
c = 120
for i in range(11): 
    new = "https://www.yelp.com/biz/eleven-madison-park-new-york?start="+str(c)+"&sort_by=date_desc"
    urls.append(new)
    c+=20
Reviews_mad = []
print(urls)
for url in urls:
    html = urlopen(url)
    bsObj4 = BeautifulSoup(html)
    reviewers = bsObj4.find_all('div', {'itemprop': 'review'})
    for name in reviewers:
        Reviews_mad.append(name.get_text())

['https://www.yelp.com/biz/eleven-madison-park-new-york?start=120&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=140&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=160&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=180&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=200&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=220&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=240&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=260&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=280&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=300&sort_by=date_desc', 'https://www.yelp.com/biz/eleven-madison-park-new-york?start=320&sort_by=date_desc']

In [47]:
Ratings_mad = []
# print(urls)
for url in urls:
    html = urlopen(url)
    bsObj4 = BeautifulSoup(html)
    
    print(url)    
    for reviewBody in bsObj4.findAll('div',{"class":"review-content"}):
        Ratings_mad.append(reviewBody.div.div.div.get("title"))

https://www.yelp.com/biz/eleven-madison-park-new-york?start=120&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=140&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=160&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=180&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=200&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=220&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=240&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=260&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=280&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=300&sort_by=date_desc
https://www.yelp.com/biz/eleven-madison-park-new-york?start=320&sort_by=date_desc

In [ ]:
for url in urls:
    html = urlopen(url)
    bsObj4 = BeautifulSoup(html)      
    for reviewBody in bsObj4.findAll('div',{"class":"review-content"}):
        Ratings_mad.append(reviewBody.div.div.div.get("title"))

In [48]:
print(len(Ratings_mad))

220

In [49]:
print(len(Reviews_mad))

220

In [50]:
yelp_combined = [{'Review': Reviews_mad,'Rating':Ratings_mad}]

In [51]:
yelp_data = pd.DataFrame({'Review': Reviews_mad,'Rating':Ratings_mad})

In [53]:
yelp_data.head(100)

             Rating                                             Review
0   5.0 star rating  \n\n\n\n\n\nMy boyfriend and I had an amazing ...
1   5.0 star rating  \n\n\n\n\n\nOk where do I start \nI think if y...
2   4.0 star rating  \n\n\n\n\n\nOutstanding dining experience at E...
3   3.0 star rating  \n\n\n\n\n\nThe food other than the dessert wa...
4   3.0 star rating  \n\n\n\n\n\nOk, if this was just another regul...
5   3.0 star rating  \n\n\n\n\n\nDisappointing. Can't believe this ...
6   5.0 star rating  \n\n\n\n\n\nLoved came with a hot escort and h...
7   2.0 star rating  \n\n\n\n\n\nWas treated to a meal here by a fr...
8   4.0 star rating  \n\n\n\n\n\nI had lunch here in July, it was m...
9   5.0 star rating  \n\n\n\n\n\nI came here for a birthday dinner ...
10  2.0 star rating  \n\n\n\n\n\nMe and my wife travel a lot and ha...
11  5.0 star rating  \n\n\n\n\n\nEleven Madison park has now become...
12  5.0 star rating  \n\n\n\n\n\nFrom our experience at my recent 2...
13  5.0 star rating  \n\n\n\n\n\nEMP had been on our radar for seve...
14  5.0 star rating  \n\n\n\n\n\nEleven Madison Park was on my frie...
15  3.0 star rating  \n\n\n\n\n\nOverrated! Every dish is over salt...
16  2.0 star rating  \n\n\n\n\n\nI've been holding off on writing t...
17  5.0 star rating  \n\n\n\n\n\nThis place is a dream! One of the ...
18  4.0 star rating  \n\n\n\n\n\nQuite a belated review, as I dined...
19  2.0 star rating  \n\n\n\n\n\nWe have been there twice and its n...
20  5.0 star rating  \n\n\n\n\n\nThe mixologist is on point, the st...
21  4.0 star rating  \n\n\n\n\n\nGood meal. I enjoyed some of the d...
22  4.0 star rating  \n\n\n\n\n\nLooking at the past couple of year...
23  4.0 star rating  \n\n\n\n\n\nChecked into this high end restaur...
24  4.0 star rating  \n\n\n\n\n\nMy friend and I had dinner at Elev...
25  5.0 star rating  \n\n\n\n\n\nMore than anticipated. Very comfor...
26  3.0 star rating  \n\n\n\n\n\nReading some of these detailed rev...
27  1.0 star rating  \n\n\n\n\n\nThe price they asking is just outr...
28  2.0 star rating  \n\n\n\n\n\nVERY BAD SERVICE. I went to EMP tw...
29  5.0 star rating  \n\n\n\n\n\nDining at Eleven Madison Park was ...
..              ...                                                ...
70  2.0 star rating  \n\n\n\n\n\nI've been to a lot of fine dining ...
71  4.0 star rating  \n\n\n\n\n\nWe came here for dinner this past ...
72  5.0 star rating  \n\n\n\n\n\nDefinitely deserving of all three ...
73  5.0 star rating  \n\n\n\n\n\nExcellent food and service without...
74  5.0 star rating  \n\n\n\n\n\nI have been fortunate enough to di...
75  5.0 star rating  \n\n\n\n\n\nEthereal.  Have the good fortune t...
76  5.0 star rating  \n\n\n\n\n\nBeautiful place. Great food. The s...
77  5.0 star rating  \n\n\n\n\n\nThis place has amazing service and...
78  5.0 star rating  \n\n\n\n\n\nMy wife and I had the Dining Room ...
79  5.0 star rating  \n\n\n\n\n\nSo hard to get into, but so worth ...
80  3.0 star rating  \n\n\n\n\n\nEvery dish was too salty for me, e...
81  5.0 star rating  \n\n\n\n\n\nIn one word. Perfection. I was sur...
82  4.0 star rating  \n\n\n\n\n\nThis place has plenty of people wh...
83  5.0 star rating  \n\n\n\n\n\nWow wow wow, what a place. The foo...
84  2.0 star rating  \n\n\n\n\n\nFinally we have decided to try out...
85  5.0 star rating  \n\n\n\n\n\nThe spring/summer menu heavily fea...
86  2.0 star rating  \n\n\n\n\n\nAfter 4+ years of living in New Yo...
87  5.0 star rating  \n\n\n\n\n\nBest dining experience!! 5 star se...
88  5.0 star rating  \n\n\n\n\n\nThere isn't much more that can be ...
89  5.0 star rating  \n\n\n\n\n\nI was there in 2016 and it was my ...
90  5.0 star rating  \n\n\n\n\n\nWe dined at EMP tonight to celebra...
91  5.0 star rating  \n\n\n\n\n\nWent for a drink in the bar/lounge...
92  2.0 star rating  \n\n\n\n\n\nBland, everything about this resta...
93  4.0 star rating  \n\n\n\n\n\nTruly lived up to all the hype. Al...
94  4.0 star rating  \n\n\n\n\n\n2 star food, 3 star service, 4 sta...
95  5.0 star rating  \n\n\n\n\n\nFabulous fabulous dinner! We went ...
96  3.0 star rating  \n\n\n\n\n\nEleven Madison Park pre-renovation...
97  3.0 star rating  \n\n\n\n\n\nI honestly can't write an in-depth...
98  5.0 star rating  \n\n\n\n\n\nAt the risk of sounding Pollyanna-...
99  4.0 star rating  \n\n\n\n\n\nPerhaps my anticipation for the me...

[100 rows x 2 columns]

In [62]:
yelp_data['Review'] = [i.replace('\n', '') for i in yelp_data['Review']]

In [64]:
yelp_data.head()

            Rating                                             Review
0  5.0 star rating        My boyfriend and I had an amazing experi...
1  5.0 star rating        Ok where do I start  I think if you rese...
2  4.0 star rating        Outstanding dining experience at Eleven ...
3  3.0 star rating        The food other than the dessert was most...
4  3.0 star rating        Ok, if this was just another regular ole...

In [ ]:
yelp_data.to_csv("yelp_data.csv")